---
categories:
   added: New features
   fixed: Bug fixes
   changed: Feature changes
   deprecated: New deprecations
   removed: Feature removals
   security: Security fixes
   performance: Performance improvements
   other: Other
